add InsecureSkipServerNameVerify to tls.Config
refraction-networking/utls pull request #158
Opened 2023-02-04 14:41 UTC by TNQOYxNU

2023-02-04 20:13 UTC, gaukas requested changes

2023-02-04 20:13 UTC, gaukas commented on handshake_client.go
>  		return nil, nil, errors.New("tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config")
Could you please also update the error message to reflect your changes made to `Config`

2023-02-04 20:13 UTC, gaukas commented on u_conn.go
>  		return errors.New("tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config")
This line as well

2023-02-04 20:17 UTC, gaukas commented
Also `go test` has failed. Please fix referring to the error message below: 
```
=== RUN   TestCloneNonFuncFields
    tls_test.go:834: all fields must be accounted for, but saw unknown field "InsecureSkipServerNameVerify"
```

2023-02-04 21:09 UTC, gaukas approved these changes

2023-02-04 21:10 UTC, gaukas commented
Thanks! I will now get this merged.

2023-02-04 21:10 UTC, merged

2023-02-05 10:33 UTC, RPRX commented
Nice work! But it would be better that if we can indicate another ServerName to verify, see https://github.com/refraction-networking/utls/pull/161